#!/bin/sh

# PROVIDE: excolonycoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# excolonycoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable excolonycoin service.
# excolonycoin_config (path): Set to /usr/local/etc/excolonycoin.conf by default.
# excolonycoin_user:  The user account excolonycoin daemon runs as. It uses 'root' user by default.
# excolonycoin_group: The group account excolonycoin daemon runs as. It uses 'wheel' group by default.
# excolonycoin_datadir (str): Default to "/var/db/excolonycoin". Base data directory.

. /etc/rc.subr

name=excolonycoin
rcvar=excolonycoin_enable

: ${excolonycoin_enable:=NO}
: ${excolonycoin_config=/usr/local/etc/excolonycoin.conf}
: ${excolonycoin_datadir=/var/db/excolonycoin}
: ${excolonycoin_user="root"}
: ${excolonycoin_group="wheel"}

required_files=${excolonycoin_config}
command=/usr/local/bin/excolonycoind
excolonycoin_chdir=${excolonycoin_datadir}
pidfile="${excolonycoin_datadir}/excolonycoind.pid"
stop_cmd=excolonycoin_stop
command_args="-conf=${excolonycoin_config} -datadir=${excolonycoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

excolonycoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${excolonycoin_datadir}
	[ $? -eq 0 ] && chown -R ${excolonycoin_user}:${excolonycoin_group} ${excolonycoin_datadir}
}

excolonycoin_prestart()
{
	if [ ! -d "${excolonycoin_datadir}/." ]; then
		excolonycoin_create_datadir || return 1
	fi
}

excolonycoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

excolonycoin_stop()
{
    excolonycoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${excolonycoin_config} -datadir=${excolonycoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
